name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Concurrent Downloads
      id: concurrent-downloads
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Concurrent Downloads
        setup-command: wget -q --no-cache https://raw.githubusercontent.com/amigler/357-s24/main/autograder/a4/ag.sh
        command: bash ag.sh concurrent
        timeout: 5
        max-score: 3
    - name: Concurrent Downloads
      id: concurrent-downloads
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Concurrent Downloads
        setup-command: wget -q --no-cache https://raw.githubusercontent.com/amigler/357-s24/main/autograder/a4/ag.sh
        command: bash ag.sh concurrent
        timeout: 5
    - name: Valgrind Check
      id: valgrind-check
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Valgrind Check
        setup-command: wget -q --no-cache https://raw.githubusercontent.com/amigler/357-s24/main/autograder/a4/ag.sh
        command: bash ag.sh valgrind
        timeout: 5
    - name: Style Check
      id: style-check
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Style Check
        setup-command: wget -q --no-cache https://raw.githubusercontent.com/amigler/357-s24/main/autograder/a4/ag.sh
        command: bash ag.sh style
        timeout: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CONCURRENT-DOWNLOADS_RESULTS: "${{steps.concurrent-downloads.outputs.result}}"
        VALGRIND-CHECK_RESULTS: "${{steps.valgrind-check.outputs.result}}"
        STYLE-CHECK_RESULTS: "${{steps.style-check.outputs.result}}"
      with:
        runners: concurrent-downloads,concurrent-downloads,valgrind-check,style-check
